# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f10ea4b40f6337f7fa88be311bc9ec57d0b5276e60b7cfb63ea2dbedbbe7dc595bd8c9c827912638ce1498758efd381d0fc1f56dce44bb478b57f075e7a65c1a

test:
  secret_key_base: ce92e971c1cd1333556b621d2f8bd23fe62fcede40dfbb84b4ca4c0eeef343b070ee5c294ca8ee4f63a3166464e3db231f25385fe646c7fb58e24d7eacbdf12d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
